services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # UI Web per il management
    environment:
      - RABBITMQ_DEFAULT_USER=aapt_user
      - RABBITMQ_DEFAULT_PASS=aapt_secret_pw # Usa una password più sicura in produzione

  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    ports:
      - "7474:7474" # UI Web per il browser Neo4j
      - "7687:7687" # Porta per il protocollo Bolt
    environment:
      - NEO4J_AUTH=neo4j/aapt_secret_db_pw # Usa una password più sicura
    volumes:
      - neo4j_data:/data

  nmap_worker:
    build: ./workers/nmap_worker # Dice a Docker Compose di costruire l'immagine da questo path
    container_name: nmap_worker
    depends_on: # Il worker non parte se RabbitMQ e Neo4j non sono pronti
      - rabbitmq
      - neo4j
    environment: # Passiamo le credenziali come variabili d'ambiente
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=aapt_user
      - RABBITMQ_PASS=aapt_secret_pw
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=aapt_secret_db_pw
      - NMAP_PORTS=22,80,443,8080,3389,445,21,23,25,53,110,139,143,3306,5432,5900,8081,8443
      - NMAP_TIMEOUT=30s
      - NMAP_TOP_PORTS=100
    command: python main.py
    ports:
      - "8080:8080" # Healthcheck HTTP

  nuclei_worker:
    build: ./workers/nuclei_worker
    container_name: nuclei_worker
    depends_on:
      - rabbitmq
      - neo4j
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=aapt_user
      - RABBITMQ_PASS=aapt_secret_pw
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=aapt_secret_db_pw
      - NUCLEI_TIMEOUT=300
      - NUCLEI_SEVERITY=low,medium,high,critical
    command: python main.py
    ports:
      - "8082:8080" # Healthcheck HTTP nuclei_worker

  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=aapt_user
      - RABBITMQ_PASS=aapt_secret_pw
      - ORCH_HEALTH_PORT=8080
    command: python main.py
    ports:
      - "8080:8080" # Healthcheck HTTP orchestrator

  orchestrator_v2:
    build: ./orchestrator
    container_name: orchestrator_v2
    depends_on:
      - rabbitmq
      - neo4j
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=aapt_user
      - RABBITMQ_PASS=aapt_secret_pw
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=aapt_secret_db_pw
      - ORCH_HEALTH_PORT=5151
    volumes:
      - ../models:/app/models  # Monta i modelli LLM
    command: python orchestrator_v2.py
    ports:
      - "5151:5151" # Healthcheck HTTP orchestrator V2
    profiles:
      - autonomous  # Solo quando si vuole usare la modalità autonoma

  ui:
    build: ./ui
    container_name: aapt_ui
    ports:
      - "5000:5000" # Dashboard web
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=aapt_user
      - RABBITMQ_PASS=aapt_secret_pw
    command: python app.py

  msf_worker:
    build: ./workers/msf_worker
    container_name: msf_worker
    depends_on:
      - rabbitmq
      - neo4j
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=aapt_user
      - RABBITMQ_PASS=aapt_secret_pw
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=aapt_secret_db_pw
    command: python3 main.py
    # Metasploit non espone porte di default

  privesc_worker:
    build: ./workers/privesc_worker
    container_name: privesc_worker
    depends_on:
      - rabbitmq
      - neo4j
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=aapt_user
      - RABBITMQ_PASS=aapt_secret_pw
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=aapt_secret_db_pw
    command: python3 main.py

volumes:
  neo4j_data: # Volume persistente per non perdere i dati del grafo 